import MainLayout from "../layouts/MainLayout";
import Link from "next/link";
import Head from "next/head";
import {GetServerSideProps} from "next";

type CategoryType = {
   id: string
   Description: string
}

type CatalogPageType = {
   categories: CategoryType[]
}

function Catalog({categories}: CatalogPageType) {
   return (
      <MainLayout>
         <Head>
            <title>Импрорт Гарант каталог</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
         </Head>
         <div className="catalog">
            <Link href="/catalog/meet">
               <a className='catalog-item' style={{display: 'block'}}>meet</a>
            </Link>
            <Link href="/catalog/milk">
               <a className='catalog-item' style={{display: 'block'}}>milk</a>
            </Link>
            <Link href="/catalog/drinks">
               <a className='catalog-item' style={{display: 'block'}}>drinks</a>
            </Link>
         </div>

      </MainLayout>
   )

}

export const getServerSideProps: GetServerSideProps = async () => {
   // Fetch data from external API
   const categories: CategoryType[] = [
      {
         id: '123',
         Description: 'Мясная продукция'
      },
      {
         id: '1232',
         Description: 'Молочная продукция'
      },
      {
         id: '1243',
         Description: 'Мясная продукция'
      },
      {
         id: '1223',
         Description: 'Мясная продукция'
      }

   ]

   // Pass data to the page via props
   return {props: {categories}}
}


export default Catalog;