import MainLayout from "../layouts/MainLayout";
import Head from "next/head";
import Link from "next/link";

type CategoryType = {
   Ref_Key: string
   Description: string
   IsFolder: boolean
   Parent_Key: string
}

type CatalogPageType = {
   categories: CategoryType[]
}

function Categories({categories}: CatalogPageType) {
   const filteredCategories = categories.filter(el=> el.IsFolder)
   console.log(filteredCategories)

   return (
      <MainLayout>
         <Head>
            <title>Импрорт Гарант каталог</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
         </Head>
         <div>
            {filteredCategories.map(el=> {
               return (
                  <li key={el.Ref_Key}>
                     <Link href={`categories/${el.Ref_Key}`}>
                        <a  style={{display: 'block'}} key={el.Ref_Key}>
                           {el.Description}
                        </a>
                     </Link>
                  </li>

               )
            })}
         </div>


      </MainLayout>
   )

}


export async function getStaticProps() {
   const res = await fetch('http://test2.komplex-info.ru/get_data.php?id=0')
   const categories = await res.json()
   return {props: {categories: categories.value}}
}


export default Categories;