import type {NextPage} from 'next'
import Head from 'next/head'
import MainLayout from "../layouts/MainLayout";

const Home: NextPage = () => {



   return (
      <MainLayout>
         <Head>
            <title>Импрорт Гарант</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
         </Head>
         <div>главная</div>

      </MainLayout>
   )
}

export default Home
